### PR TITLE
Give a meaner error message when null is passed

### PR DESCRIPTION
**Pull request by rjernst**

### CODE REVIEW

**Comment by rmuir** [comment]
I don't agree with being nice. No where else in the JDK passes "nice" NullPointerExceptions. In fact I think this method on Objects shoudl be banned, why be inconsistent? Why should we do it here?

**Comment by rmuir** [comment]
I am willing to reconsider this PR, if the error message can somehow be _mean_. For example, it could insult the caller for their stupidity.

**Comment by s1monw** [comment]
I don't know what @rjernst was thinking here opening this over-engineered checks all over the place. This is just going to send the wrong message to other contributors.

**Comment by rmuir** [comment]
@s1monw I agree. I also have big big concerns that "being nice" is gonna send the wrong message to users as well. First its being nice, next someone wants leniency in the parser.

**Comment by jdconrad** [comment]
Can we add "yes" as something that can be true to match the native one?  I think users would really like that.

**Comment by rmuir** [comment]
I updated the title and labels to reflect the current situation.

**Comment by rmuir** [comment]
Still deserves some thought. The implicit null-check defined for the switch-on-string still has some nice qualities about it: it has no text at all to give you any hint where it came from. Having an empty message is particularly awesome when applications throw the stacktrace in the trash can like:

```
Nested: NullPointerException
```

If we provide a message, we discourage them from from fixing their broken stacktrace handling. The stacktrace already makes it clear its a NPE from BooleanParser.parseBoolean(). Why should we have to repeat ourselves here?

**Comment by rjernst** [comment]
I improved the error message. To me, degrading the user is more important than the cost of an extra line, or the potential to "help" them find their problem, but I see your point.

**Comment by rmuir** [comment]
I thought about this a lot more, and there a number of reasons why I think a "pure" `NullPointerException` is best:

As mentioned above, this is consistent with `NullPointerException` coming from the JDK in other methods. Who knows, we might want to make a JEP proposal to add `Boolean.parseBooleanExact()` with these semantics so its in the JDK for everyone. In my opinion its really missing: parsers for other primitive types are somewhat more sane and only `boolean/Boolean` is defined in a totally insane way. 

The use of `null` is a certain programmer error. I think java developers tend to like `Boolean.parseBoolean` because it "saves them" code, but I insist it only causes confusion. Which of the following is better?

```
Boolean.parseBoolean(System.getProperty("important_parameter"));
Boolean.parseBooleanExact(System.getProperty("important_parameter", "false"));
```

Maybe developers think the first one is faster: e.g. it avoids parsing for a `null` condition. BooleanParser intentionally trades off any optimizations for simplicity because I am thoroughly convinced that boolean parsing is never the bottleneck in any application. Instead, its better to be clear about what default values are in the code, and its better to be strict in all possible contexts. 

I think boolean parsing is important enough that `null` should never have a meaning, its just a programmer error. If someone disagrees about that, they can build a crappy `parseWithDefault(String,boolean)` on top that interprets `null` in some special way. 

Like the JDK, we don't need a message. Only a stacktrace is necessary, so the programmer can go fix their code.

I do really like the idea of insulting the developer if they screw up, and the message in this PR is a good one, but I also don't want to discourage people from parsing booleans correctly because they think this library will make their application appear "unprofessional". Instead I think we should encourage parsing booleans correctly in all applications.

**Pull request closed without merging**
